name: "scenario3-deploy"

on:
  push:
    branches: [$default-branch]
    paths:
      - "infra/scenario3/**"
      - ".github/workflows/deploy.yaml"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    #runs-on: ubuntu-latest
    runs-on: [self-hosted]
    environment: scenario3
    env:
      INFRA_WORKING_DIRECTORY: "infra/scenario3"
      AZURE_APIM_PUBLISHER_EMAIL: ${{ vars.AZURE_APIM_PUBLISHER_EMAIL }}
      AZURE_APIM_PUBLISHER_NAME: ${{ vars.AZURE_APIM_PUBLISHER_NAME }}
      AZURE_APIM_SUBNET_NAME: ${{ vars.AZURE_APIM_SUBNET_NAME }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_FUNCTION_APP_SUBNET_NAME: ${{ vars.AZURE_FUNCTION_APP_SUBNET_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_LOGIC_APP_SUBNET_NAME: ${{ vars.AZURE_LOGIC_APP_SUBNET_NAME }}
      AZURE_PRIVATE_ENDPOINT_SUBNET_NAME: ${{ vars.AZURE_PRIVATE_ENDPOINT_SUBNET_NAME }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_SQL_ADMIN_OBJECT_ID: ${{ vars.AZURE_SQL_ADMIN_OBJECT_ID }}
      AZURE_SQL_ADMIN_USERNAME: ${{ vars.AZURE_SQL_ADMIN_USERNAME }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_VIRTUAL_NETWORK_NAME: ${{ vars.AZURE_VIRTUAL_NETWORK_NAME }}
      AZURE_VIRTUAL_NETWORK_RESOURCE_GROUP_NAME: ${{ vars.AZURE_VIRTUAL_NETWORK_RESOURCE_GROUP_NAME }}
      AZURE_WEBSITE_DNS_SERVER: ${{ vars.AZURE_WEBSITE_DNS_SERVER }}
      RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
      RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
      RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          terraform init \
          -input=false
          -backend-config="storage_account_name=${{ env.RS_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ env.RS_CONTAINER_NAME }}" \
          -backend-config="key=azd/azd.tfstate" \
          -backend-config="resource_group_name=${{ env.RS_RESOURCE_GROUP }}"
        working-directory: ${{ env.INFRA_WORKING_DIRECTORY }}

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ env.INFRA_WORKING_DIRECTORY }}

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ${{ env.INFRA_WORKING_DIRECTORY }}

        # On push to $default-branch, build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        if: github.ref == 'refs/heads/$default-branch' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.INFRA_WORKING_DIRECTORY }}
